myapp/urls.py
from django.urls import path
from .views import add_item, update_item, delete_item, ProductListView, ProductDetailView, ProductDeleteView

app_name= "myapp" #добавление пространства имен (namespace) в проект

urlpatterns = [
    path('', ProductListView.as_view(), name="index"),
    path("<int:pk>/", ProductDetailView.as_view(), name="detail"),
    path("additem/", add_item, name="add_item"),
    path("updateitem/<int:my_id>/", update_item, name="update_item"),
    path("deleteitem/<int:pk>/", ProductDeleteView.as_view(), name="delete_item"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("myapp.urls", namespace="myapp")),
    # namespace предотвращает конфликты для одинаковых имен путей (urls) из разных приложений
    path('users/', include("users.urls", namespace="users")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import *

app_name= "users" #добавление пространства имен (namespace) в проект

urlpatterns = [
    path("register/", register, name="register"),
    path("login/", LoginView.as_view(template_name='users/login.html'), name="login"),
    path("logout/", LogoutView.as_view(template_name='users/logout.html'), name="logout"),
    path("profile/", profile, name="profile"),
    path("sellerprofile/<int:id>/", seller_profile, name="sellerprofile"),
]

myapp/models.py
from django.db import models
from django.contrib.auth.models import User



class Product(models.Model):
    seller = models.ForeignKey(User, on_delete=models.CASCADE, default='1')
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    description = models.CharField(max_length=250)
    image = models.ImageField(blank=True, upload_to="images")

    def __str__(self):
        return self.name

users/models.py
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(blank=True, upload_to='_profile_images')
    contact_number = models.CharField(max_length=50, default='+79123456789')

    def __str__(self):
        return self.user.username

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class NewUserForm(UserCreationForm):
    email = forms.EmailField(
        required=True,
        widget=forms.EmailInput(
            attrs={"class":"focus:outline-none", "placeholder":"mail@mail.com"}
        )),

    username = forms.CharField(
        required=True,
        widget=forms.TextInput(
            attrs={"class":"focus:outline-none", "placeholder":"Enter username"}
        )),
    password1 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(
            attrs={"class":"focus:outline-none", "placeholder":"Enter password"}
        )),
    password2 = forms.CharField(
        required=True,
        widget=forms.PasswordInput(
            attrs={"class":"focus:outline-none", "placeholder":"Enter same password"}
        )),

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")


    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        return user

myapp/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import DeleteView
from django.urls import reverse_lazy

from .models import Product

# def index(request):
#     items = Product.objects.all()
#     context = {
#         'items':items
#     }
#     return render(request, "myapp/index.html", context)


class ProductListView(ListView):
    model = Product
    template_name = "myapp/index.html"
    context_object_name = "items"
    paginate_by = 2

# def indexItem(request, my_id):
#     item = Product.objects.get(id=my_id)
#     context = {
#         'item':item
#     }
#     return render(request, "myapp/detail.html", context)

class ProductDetailView(DetailView):
    model = Product
    template_name = "myapp/detail.html"
    context_object_name = "item"
    paginate_by = 2



@login_required
def add_item(request):
    if request.method == "POST":
        name = request.POST.get("name")
        price = request.POST.get("price")
        description = request.POST.get("description")
        image = request.FILES['upload']
        seller = request.user
        item = Product(name=name, price=price, description=description, image=image, seller=seller)
        item.save()
    return render(request, "myapp/additem.html")


def update_item(request, my_id):
    item = Product.objects.get(id=my_id)
    if request.method == "POST":
        item.name = request.POST.get("name")
        item.price = request.POST.get("price")
        item.description = request.POST.get("description")
        item.image = request.FILES.get('upload', item.image)
        item.save()
        return redirect("/")
    context = {
        'item': item
    }
    return render(request, "myapp/updateitem.html", context)


def delete_item(request, my_id):
    item = Product.objects.get(id=my_id)
    if request.method == "POST":
        item.delete()
        return redirect("/")
    context = {'item': item}
    return render(request, "myapp/deleteitem.html", context)


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy("myapp:index")

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

from .forms import NewUserForm
from .models import Profile


def register(request):
    if request.method == "POST":
        form = NewUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('myapp:index')
    form = NewUserForm()
    context = {"form": form}
    return render(request, 'users/register.html', context)

@login_required #декоратор необходимый для разграничения доступа (при условии что пользователь не аутентифицирован, при обращении по адресу /users/profile/ будет возникать ошибка 404)
def profile(request):
    if request.method == "POST":
        image = request.FILES['upload_profile_images']
        contact_number = request.POST.get("contact_number")
        profile_user = Profile(image=image, contact_number=contact_number)
        profile_user.save()
    return render(request, 'users/profile.html')

def seller_profile(request, id):
    seller = User.objects.get(id=id)

    context = {'seller': seller}
    return render(request, 'users/sellerprofile.html', context)

myapp/templates/myapp/additem.html
{% extends "myapp/base.html" %}

{% block content %}
<div class="ml-[200px]">
  <h1 class="text-2xl m-10 font-bold text-green-600"> Add New Item Bellow</h1>

  <form class="w-1/3 bg-white shadow-md m-10 px-8 py-8" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-4">
      <label class="block text-gray-700 text-md font-bold mb-2" for="name">Item name</label>
      <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text" placeholder="Name.." name="name" id="name">
      <label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="price">Item Price</label>
      <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text" placeholder="Price.." name="price" id="price">
      <label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="description">Item Description</label>
      <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text" placeholder="Description.." name="description" id="description">
      <input class="block mt-4" type="file" accept="image/*" name="upload" id="upload">
      <button class="block bg-green-600 text-white p-3 mt-4" type="submit" name="Add Item" value="Add Item"> Add Item </button>
    </div>
  </form>
</div>

{% endblock content %}

myapp/templates/myapp/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="{% static 'myapp/styles.css' %}">
  <title>Document</title>
</head>
<body>

<!--  Подключение навбара из navbar.html -->
{% include "myapp/navbar.html" %}

  {% block content %}
    В данных блоках будут находиться части контента определенные для других шаблонов, то есть здесь обозначается переменная часть контента
  {% endblock content %}
</body>
</html>

myapp/templates/myapp/deleteitem.html
{% extends "myapp/base.html" %}

{% block content %}
<h1 class="text-2xl m-10 font bold">Delete Product</h1>
<form class="bg-white shadow-md m-10 w-3/5 rounded px-8 pt-6 pb-8 mb-4" method="post">
  {% csrf_token %}
  <div class="mb-4">
    <label class="block text-gray text-sm font mb-2">Are You sure You want to delete this item</label>
    <label class="block text-gray text-sm font mb-2">{{ item.name }}</label>
    <img class="w-40 h-40" src="{{ item.image.url }}" alt="" srcset="">
  </div>
  <input class="bg-red-500 text-white px-5 py-2" type="submit" value="Confirm">
  <a class="button bg-green-500 text-white px-5 py-3" href="{% url 'myapp:index' %}">Cancel</a>
</form>
{% endblock content %}

myapp/templates/myapp/detail.html
{% extends "myapp/base.html" %}
{% load humanize %}

{% block content %}

<div class="flex p-10 w-full h-200">
  <img class="w-1/3" src="{{ item.image.url }}" alt="{{ item.name }}">
  <div class="w-2/3 text-xl ml-10 mt-5">
    <p class="mt-5">{{ item.name }}</p>
    <p class="mt-5 text-green-500">$ {{ item.price | intcomma }}</p>
    <p class="mt-5 text-green-500"><a href="{% url 'users:sellerprofile' item.seller.id %}">@{{ item.seller }}</a></p>
    <p class="mt-5 text-green-500">{{ item.seller.profile.contact_number }}</p>
    <p class="mt-5 text-gray-600">{{ item.description }}</p>
    <button class="bg-green-500 text-white mt-[50px]"><a href="{% url 'myapp:update_item' item.id %}">Update Item</a></button>
    <button class="bg-red-500 text-white mt-[50px]"><a href="{% url 'myapp:delete_item' item.id %}">Delete Item</a></button>
  </div>
</div>

{% endblock content %}

myapp/templates/myapp/index.html
{% extends "myapp/base.html" %}
{% load humanize %}

{% block content %}
<main class="mt-10 mx-auto max-w-7x1 px-4 sm:mt-12 sm:px-6 md:16 lg:mt-20 lg:px-8 xl:mt-28">
  <div class="sm:text-center lg:text-left">
    <h1 class="text-4xl font-extrabold text-gray-900 sm:text-5xl md:text-6xl">
      <span class="block xl:inline">ЭКСКЛЮЗИВНЫЕ ТОВАРЫ </span><br>
      <span class="block xl:inline text-green-500">ПО СУПЕР ЦЕНАМ</span>
    </h1>
    <p class="mt-3 text-base text-gray-500 sm:mt-5 sm:text-lg sm:max-w-xl sm:mx:-auto md:mt-5 md:text-xl lg:mx-0">Вы можете заказать товар из любой точки мира. Доставка включена</pclass>
  </div>


<!--  <div class="mt-5 p-10 justify-center">-->
<!--    <h2>Search</h2>-->
<!--    <form action="" method="get">-->
<!--      <input type="text" name="search" placeholder="Search...">-->
<!--    </form>-->
<!--  </div>-->


  <div class="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 xl:grid-col-3 lg:grid-col-3 gap-3">

    {% for item in items %}

    <!--    <a href="/home/{{ item.id }}/"> <h2>Название: {{ item.name }}</h2></a>-->
    <a href="{% url 'myapp:detail' item.id %}">
      <div class="rounded overflow-hidden shadow-lg">
        <img class="h-18 w-18" src="{{ item.image.url }}" alt="">
        <div class="px-6 py-4">
          <p class="font-bold text-xl mb-2">{{ item.name }}</p>
          <p class="font-bold text-xl text-green-500 mb-2">$ {{ item.price | intcomma }}</p>
          <p class="font-bold text-xl text-indigo-500 mb-2">By: {{ item.seller }}</p>
          <p class="text-gray-700 text-base">{{ item.description }}</p>
        </div>
      </div>
      <!--    запись 'myapp:detail' предотвращает конфликты для одинаковых имен путей (urls) из разных приложений - это называется пространством имен-->
      <!--    {% url 'myapp:detail' item.id %} данная запись позволяет генерировать пути с помощью имени  пути (name в urls)-->
    </a>

    {% endfor %}

  </div>

  <form>
    <span>
      {% if page_obj.has_previous %}
        <a href="?page=1">First</a>
        <a href="?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}
    </span>

    <span>
      {{ page_obj }}
    </span>

    <span>
      {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">Next</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}
    </span>
  </form>
</main>

{% endblock content %}

myapp/templates/myapp/navbar.html
{% load static %}
<nav class="bg-white shadow-lg">
    <diV class="max-w-6x1 mx-auto px-4">
        <div class="flex justify-between">
            <div class="flex space-x-7">
                <div>
                    <a href="{% url 'myapp:index' %}" class="flex items-center px-2 py-4">
                    <img class="h-8 w-8" src="{% static 'myapp/images/shop.png' %}" alt="logo" />
                    <span class="text-gray-500 font-semibold text-xl">Shop</span>
                    </a>
                </div>
                <div class="items-center flex space-x-1">
                        <!--Все свойства в klass берутся из файла styles.css который сформирован через tailwinds.
                        Tailwinds должен быть включен для генерации стилей (команда npm run build, где команда build прописывалась
                        вручную в файле package.json (подробнее на сайте tailwinds)-->
                    <a href="{% url 'myapp:index' %}" class="py-4 px-2 text gray-500 font-semibold border-b-4 border-green-500">Home</a>
                    <a href="{% url 'myapp:add_item' %}" class="py-4 px-2 text gray-500 font-semibold">Add item</a>
                    <a href="#" class="py-4 px-2 text gray-500 font-semibold">Contacts</a>
                    {% if user.is_authenticated %}
                        <a class="py-4 px-2 text gray-500 font-semibold" href="{% url 'users:logout' %}">Logout</a>
                        <a class="py-4 px-2 text gray-500 font-semibold" href="{% url 'users:profile' %}">Profile</a>
                        {% else %}
                        <a class="py-4 px-2 text gray-500 font-semibold" href="{% url 'users:login' %}">Login</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </diV>
</nav>

myapp/templates/myapp/product_confirm_delete.html
<form action="" method="post">
  {% csrf_token %}
  <p>Do you want to delete? {{ object }}</p>
  <input type="submit" value="Delete">
</form>

myapp/templates/myapp/updateitem.html
{% extends "myapp/base.html" %}

{% block content %}
<div class="ml-[200px]">
  <h1 class="text-2xl m-10 font-bold text-green-600"> Update New Item</h1>

  <form class="w-1/3 bg-white shadow-md m-10 px-8 py-8" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="mb-4">
      <label class="block text-gray-700 text-md font-bold mb-2" for="name">Item name</label>
      <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" value="{{ item.name }}" type="text" placeholder="Name.." name="name" id="name">
      <label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="price">Item Price</label>
      <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" value="{{ item.price }}" type="text" placeholder="Price.." name="price" id="price">
      <label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="description">Item Description</label>
      <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" value="{{ item.description }}" type="text" placeholder="Description.." name="description" id="description">
      <img class="w-20 h-20" src="{{ item.image.url }}" alt="" srcset="">
      <input class="block mt-4" type="file" accept="image/*" name="upload" id="upload">
      <button class="block bg-green-600 text-white p-3 mt-4" type="submit" name="Add Item" value="Add Item"> Update Item </button>
    </div>
  </form>
</div>

{% endblock content %}

users/templates/users/login.html
{% extends "myapp/base.html" %}

{% block content %}
  <div class="container py-5">
    <h1 class="text-2xl m-10 font-bold">Login User</h1>
    <form class="w-2/5 bg-white-700 shadow-md m-10 rounded px-8 pt-6 pb-8 mb-4" method="post">
      {% csrf_token %}
      <div class="mb-2">
        <label class="block text-gray-700 text-sm font-bold mb-2">Username</label>
        <p class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">{{ form.username }}</p>
        <label class="block text-gray-700 text-sm font-bold mb-2">Password</label>
        <p class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">{{ form.password }}</p>
      </div>
      <button class="bg-green-500 text-white px-5 py-2" type="submit">Login</button>
      <button class="bg-sky-500 text-white px-5 py-2"><a href="{% url 'users:register' %}"></a>Register</button>
    </form>
  </div>
{% endblock content %}

users/templates/users/logout.html
{% extends "myapp/base.html" %}

{% block content %}
  <h1>Tou have been logout</h1>
{% endblock content %}

users/templates/users/profile.html
{% extends "myapp/base.html" %}

{% block content %}
  {% if user.profile %}

  <div class="grid p-10 grid-cols-1 lg:grid-cols-3 sm:grid-cols-1">
    <div class="rounded shadows-lg">
      <div>
        {% if user.profile.image %}
          <img class="h-18 w-18" src="{{ user.profile.image.url }}" alt="" srcset="">
        {% endif %}
      </div>
      <h1 class="font-bold text-xl m-2">{{ user.username }}</h1>
    </div>
  </div>
  {% else %}
    <h1 class="font-bold text-xl m-2">FORM Profile</h1>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="mb-4">
        <label class="block text-gray-700 text-md font-bold mb-2">Upload Profile Image</label>
        <input class="block mt-4" type="file" accept="image/*" name="upload_profile_images" id="upload_profile_images" required>
        <label class="block text-gray-700 text-md font-bold mb-2">Profile number</label>
        <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text" placeholder="Your Number" name="contact_number" id="contact_number">
      </div>
      <button class="block bg-green-600 text-white p-3 mt-4" type="submit" name="create_profile" value="create_profile"> Create Profile </button>
    </form>
  {% endif %}
{% endblock content %}

users/templates/users/register.html
{% extends "myapp/base.html" %}

{% block content %}

  <div class="container py-5">
    <h1 class="text-2xl m-10 font-bold">Register User</h1>
    <form class="w-2/5 bg-white-700 shadow-md m-10 rounded px-8 pt-6 pb-8 mb-4" method="post">
      {% csrf_token %}
      <div class="mb-2">
        <label class="block text-gray-700 text-sm font-bold mb-2">Username</label>
        <p class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">{{ form.username }}</p>
        <label class="block text-gray-700 text-sm font-bold mb-2">Email</label>
        <p class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">{{ form.email }}</p>
        <label class="block text-gray-700 text-sm font-bold mb-2">Password</label>
        <p class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">{{ form.password1 }}</p>
        <label class="block text-gray-700 text-sm font-bold mb-2">Confirm Password</label>
        <p class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700 leading-tight">{{ form.password2 }}</p>
      </div>
      <button class="bg-green-500 text-white px-5 py-2" type="submit">Register</button>
    </form>
  </div>

{% endblock content %}

users/templates/users/sellerprofile.html
{% extends "myapp/base.html" %}

{% block content %}
    <div class="grid p-10 grid-cols-1 lg:grid-cols-3 sm:grid-cols-1">
    <div class="rounded shadows-lg">
      <div>
        {% if user.profile.image %}
          <img class="h-18 w-18" src="{{ seller.profile.image.url }}" alt="" srcset="">
        {% endif %}
      </div>
      <h1 class="font-bold text-xl m-2">{{ seller.username }}</h1>
    </div>
  </div>
{% endblock content %}